services:
  redis:
    image: redis:latest
    container_name: redis_shortener
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "no", "--maxclients", "25000"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  nginx:
    image: nginx:latest
    container_name: nginx_shortener
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
      - app
    networks:
      - proxy
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
      - proxy

networks:
  backend:
    internal: true
  proxy:
    driver: bridge
