services:
  redis:
    image: redis:latest
    container_name: redis_shortner
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --maxclients 25000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
